### ISSUE TITLE
Add a CE 'watermark' on images used for CE classes, spells etc

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#455]

**Comment by DubhHerder** [comment]
Is it possible to create a new ContentPackDefinition for CE to achieve this? Setting it as the content pack for all database additions either reusing an existing asset for the GUI symbol or creating a new builder that adds a new assets via a method inline with : 

general approach
https://answers.unity.com/questions/432655/loading-texture-file-from-pngjpg-file-on-disk.html

loading of png into Solasta
https://github.com/search?q=user%3AHolic75+customicons&type=code

**Comment by PhilPJL** [comment]
We've already got some code to create a Sprite in MapGadgetItemPatcher.cs which could be used.
I'll look at the ContentPackDefinition idea.  Not sure what that is at the moment :)

The ![image](https://user-images.githubusercontent.com/271656/149222103-0042e288-9373-4f95-b97f-1269daee864c.png) or a stop sign would be useful to indicate an scroll not usable by that class.

**Comment by DubhHerder** [comment]
The content packs are how the Devs manage their dlc , and is what adds the dlc badges to the sorcerer druid and barbarian classes/subclasses and half orc race like in the following 
https://fextralife.com/wp-content/uploads/2021/07/Solasta-Sorcerer-Subclasses-1.jpg

i mentioned it because it sounds like it's a similar process and I think most database entries can be assigned a content pack but never tested it

https://github.com/SolastaMods/SolastaBlueprints/tree/main/ContentPackDefinition

That exclamation point is the GUI sprite from the critical character condition
https://github.com/SolastaMods/SolastaBlueprints/blob/main/ConditionDefinition/ConditionCriticalCharacter.eed1ab32e3f2fa84eae62bcd4c4b06f9.json

**Comment by PhilPJL** [comment]
Looks like our code only creates a Sprite and we need an AssetReferenceSprite.  Holic has code to patch AssetReference.  Bigger job than I expected.

**Comment by DubhHerder** [comment]
Might be easier to reuse an existing asset then if  the addition of new assets is not worth the effort. You could pick any random asset or reuse one of backer badges to stay on theme if that doesn't step on the Devs toes too much. To extract sprites to decide which are suitable , I used https://github.com/Perfare/AssetStudio. It's a big database so the filter is needed

I've also seen a few other mods for kingmaker for similar asset loading into PF km database

https://github.com/spacehamster/KingmakerTextureLoader

And a one page gist
https://gist.github.com/spacehamster/36af7685020093e6a4637b82b4e52068


https://github.com/RobRendell/OwlcatKingmakerModCraftMagicItems/blob/master/CraftMagicItems/Image2Sprite.cs
(I think this is where Holic got the code as it's the exact same comment as in his etc)

**Comment by PhilPJL** [comment]
Creating a Sprite is easy.  Creating an AssetReferenceSprite doesn't seem to be.
I'll have a look at the AssetStudio thanks.

**Comment by DubhHerder** [comment]
Ah ok, it's beyond me anyway. I just saw the section of holics code related to the below line and assumed there wasn't a significant difference.

'static public AssetReferenceSprite storeCustomIcon(string name, string file_path, int size_x, int size_y)' 

The extracting of assets and finding similar projects is pretty much as far as I've gotten with the topic so best of luck with it

**Comment by PhilPJL** [comment]
Closing in favour of #822
