### ISSUE TITLE
Level 20 features: Ranger: Feral Senses

### ISSUE THREAD

**Issue by ChrisPJohn** [ChrisPJohn/SolastaCommunityExpansion#81]

**Comment by DubhHerder** [comment]
**feature :**

At 18th level, you gain preternatural senses that help you fight creatures you can't see. When you attack a creature you can't see, your inability to see it doesn't impose disadvantage on your attack rolls against it. You are also aware of the location of any invisible creature within 30 feet of you, provided that the creature isn't hidden from you and you aren't blinded or deafened.

**Suggested Implementation**

add new version of  SenseSeeInvisible12 that is limited to 6 cells instead of 12

**Comment by ThyWoof** [comment]
In 1.2.15
