### ISSUE TITLE
Community Expansion 'Content Pack'

### ISSUE THREAD

**Issue by PhilPJL** [ChrisPJohn/SolastaCommunityExpansion#822]
We should set the 'contentCopyright' and 'contentPack' fields in definitions created by CE.
We may need to allow other mods to provide their own values if using CE infrastructure.
Suggestions is to base on SorcererUpdate which is in 'automaticallyUnlockedContentPacks'

**Comment by DubhHerder** [comment]
as content packs only appear on some things and not others (classes, subclasses and not spells etc) if you want to cover spells and similar you might need to consider :

* `AddTagAsNeeded` in `tagsDefinitions.cs` 
* `EnumerateTags` and `TagsMap` in `GuiSpellDefinition.cs`/`GuiPowerDefinition.cs`/`GuiMonsterDefinition.cs`/`GuiItemDefinition.cs` etc

looking at the `WarList` tag might be useful because that is related to subset of spells

**Comment by PhilPJL** [comment]
@DubhHerder Working on this on this [branch ](https://github.com/ChrisPJohn/SolastaCommunityExpansion/tree/BetaContentPack)

We have
![image](https://user-images.githubusercontent.com/271656/157890153-d1478ed7-07ea-41b1-8764-5c87472433b3.png)

![image](https://user-images.githubusercontent.com/271656/157890336-19397316-535d-486b-a97c-8740551574ec.png)

![image](https://user-images.githubusercontent.com/271656/157890790-c8619fa2-41e8-4281-9f4b-06ffb363e5f6.png)

![image](https://user-images.githubusercontent.com/271656/157890862-c2e618c6-475d-4fc7-a19c-d37225bb1861.png)

Please review the code.
Can you think of anything else.
